// Generated by ANTLR 4.1
package de.analysis.parser;
import org.antlr.v4.runtime.misc.NotNull;
import org.antlr.v4.runtime.tree.ParseTreeVisitor;

/**
 * This interface defines a complete generic visitor for a parse tree produced
 * by {@link sybaseiqParser}.
 *
 * @param <T> The return type of the visit operation. Use {@link Void} for
 * operations with no return type.
 */
public interface sybaseiqVisitor<T> extends ParseTreeVisitor<T> {
	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#expression_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitExpression_list(@NotNull sybaseiqParser.Expression_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_cursor}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_cursor(@NotNull sybaseiqParser.Declare_cursorContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#clustered}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitClustered(@NotNull sybaseiqParser.ClusteredContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#with_table_hints}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWith_table_hints(@NotNull sybaseiqParser.With_table_hintsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#query_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitQuery_expression(@NotNull sybaseiqParser.Query_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_statistics}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_statistics(@NotNull sybaseiqParser.Create_statisticsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#join_part}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitJoin_part(@NotNull sybaseiqParser.Join_partContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#predicate}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPredicate(@NotNull sybaseiqParser.PredicateContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#output_format}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOutput_format(@NotNull sybaseiqParser.Output_formatContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#replace_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitReplace_statement(@NotNull sybaseiqParser.Replace_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#use_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUse_statement(@NotNull sybaseiqParser.Use_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#optimize_for_arg}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOptimize_for_arg(@NotNull sybaseiqParser.Optimize_for_argContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_source}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_source(@NotNull sybaseiqParser.Table_sourceContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#xml_common_directives}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitXml_common_directives(@NotNull sybaseiqParser.Xml_common_directivesContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#result_column}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitResult_column(@NotNull sybaseiqParser.Result_columnContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#waitfor_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWaitfor_statement(@NotNull sybaseiqParser.Waitfor_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#goto_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitGoto_statement(@NotNull sybaseiqParser.Goto_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#set_special}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSet_special(@NotNull sybaseiqParser.Set_specialContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#option}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOption(@NotNull sybaseiqParser.OptionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_source_item}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_source_item(@NotNull sybaseiqParser.Table_source_itemContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_schema}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_schema(@NotNull sybaseiqParser.Create_schemaContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#query_specification}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitQuery_specification(@NotNull sybaseiqParser.Query_specificationContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#over_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOver_clause(@NotNull sybaseiqParser.Over_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#update_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUpdate_statement(@NotNull sybaseiqParser.Update_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#drop_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDrop_table(@NotNull sybaseiqParser.Drop_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#number}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitNumber(@NotNull sybaseiqParser.NumberContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#change_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitChange_table(@NotNull sybaseiqParser.Change_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_type_definition}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_type_definition(@NotNull sybaseiqParser.Table_type_definitionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_statement(@NotNull sybaseiqParser.Declare_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#func_proc_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFunc_proc_name(@NotNull sybaseiqParser.Func_proc_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_definition}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_definition(@NotNull sybaseiqParser.Column_definitionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#rowset_function_limited}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitRowset_function_limited(@NotNull sybaseiqParser.Rowset_function_limitedContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_value_constructor}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_value_constructor(@NotNull sybaseiqParser.Table_value_constructorContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#function_call}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFunction_call(@NotNull sybaseiqParser.Function_callContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#fetch_cursor}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFetch_cursor(@NotNull sybaseiqParser.Fetch_cursorContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#sybaseiq_file}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSybaseiq_file(@NotNull sybaseiqParser.Sybaseiq_fileContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#select_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSelect_statement(@NotNull sybaseiqParser.Select_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#full_column_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFull_column_name(@NotNull sybaseiqParser.Full_column_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_hint}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_hint(@NotNull sybaseiqParser.Table_hintContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_local}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_local(@NotNull sybaseiqParser.Declare_localContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_note}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_note(@NotNull sybaseiqParser.Create_noteContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_constraint}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_constraint(@NotNull sybaseiqParser.Table_constraintContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_alias}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_alias(@NotNull sybaseiqParser.Column_aliasContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#dml_table_source}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDml_table_source(@NotNull sybaseiqParser.Dml_table_sourceContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#grant_rights}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitGrant_rights(@NotNull sybaseiqParser.Grant_rightsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#if_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIf_statement(@NotNull sybaseiqParser.If_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#constant_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitConstant_expression(@NotNull sybaseiqParser.Constant_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#ranking_windowed_function}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitRanking_windowed_function(@NotNull sybaseiqParser.Ranking_windowed_functionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#truncate_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTruncate_statement(@NotNull sybaseiqParser.Truncate_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#wot_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWot_statement(@NotNull sybaseiqParser.Wot_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#derived_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDerived_table(@NotNull sybaseiqParser.Derived_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#another_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAnother_statement(@NotNull sybaseiqParser.Another_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_alias_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_alias_list(@NotNull sybaseiqParser.Column_alias_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#binary_operator_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBinary_operator_expression(@NotNull sybaseiqParser.Binary_operator_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_procedure}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_procedure(@NotNull sybaseiqParser.Create_procedureContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#search_condition}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSearch_condition(@NotNull sybaseiqParser.Search_conditionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#try_catch_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTry_catch_statement(@NotNull sybaseiqParser.Try_catch_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#union}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUnion(@NotNull sybaseiqParser.UnionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#log_what}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitLog_what(@NotNull sybaseiqParser.Log_whatContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#partition_by_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPartition_by_clause(@NotNull sybaseiqParser.Partition_by_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#return_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitReturn_statement(@NotNull sybaseiqParser.Return_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#comment_on_object}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitComment_on_object(@NotNull sybaseiqParser.Comment_on_objectContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_view}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_view(@NotNull sybaseiqParser.Create_viewContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#order_by_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOrder_by_expression(@NotNull sybaseiqParser.Order_by_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_set_cursor_common}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_set_cursor_common(@NotNull sybaseiqParser.Declare_set_cursor_commonContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#parameter_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitParameter_statement(@NotNull sybaseiqParser.Parameter_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_ref_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_ref_expression(@NotNull sybaseiqParser.Column_ref_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#function_call_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFunction_call_expression(@NotNull sybaseiqParser.Function_call_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#continue_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitContinue_statement(@NotNull sybaseiqParser.Continue_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#constraint_type}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitConstraint_type(@NotNull sybaseiqParser.Constraint_typeContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#group_by_item}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitGroup_by_item(@NotNull sybaseiqParser.Group_by_itemContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#execute_var_string}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitExecute_var_string(@NotNull sybaseiqParser.Execute_var_stringContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#view_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitView_name(@NotNull sybaseiqParser.View_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#as_table_alias}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAs_table_alias(@NotNull sybaseiqParser.As_table_aliasContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#unsigned_addition}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUnsigned_addition(@NotNull sybaseiqParser.Unsigned_additionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#alter_database}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAlter_database(@NotNull sybaseiqParser.Alter_databaseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#case_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCase_expression(@NotNull sybaseiqParser.Case_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#scalar_function_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitScalar_function_name(@NotNull sybaseiqParser.Scalar_function_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#select_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSelect_list(@NotNull sybaseiqParser.Select_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#bracket_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBracket_expression(@NotNull sybaseiqParser.Bracket_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#break_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBreak_statement(@NotNull sybaseiqParser.Break_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#default_value}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDefault_value(@NotNull sybaseiqParser.Default_valueContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#drop_statistics}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDrop_statistics(@NotNull sybaseiqParser.Drop_statisticsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#set_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSet_statement(@NotNull sybaseiqParser.Set_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#cursor_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCursor_name(@NotNull sybaseiqParser.Cursor_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#index_type}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIndex_type(@NotNull sybaseiqParser.Index_typeContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#drop_procedure}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDrop_procedure(@NotNull sybaseiqParser.Drop_procedureContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#primitive_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPrimitive_expression(@NotNull sybaseiqParser.Primitive_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#all_distinct_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAll_distinct_expression(@NotNull sybaseiqParser.All_distinct_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#sql_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSql_clause(@NotNull sybaseiqParser.Sql_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#bulk_option}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBulk_option(@NotNull sybaseiqParser.Bulk_optionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#on_off}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOn_off(@NotNull sybaseiqParser.On_offContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#comparison_operator}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitComparison_operator(@NotNull sybaseiqParser.Comparison_operatorContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#openquery}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOpenquery(@NotNull sybaseiqParser.OpenqueryContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#cursor_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCursor_statement(@NotNull sybaseiqParser.Cursor_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#insert_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitInsert_statement(@NotNull sybaseiqParser.Insert_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_name(@NotNull sybaseiqParser.Column_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#null_notnull}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitNull_notnull(@NotNull sybaseiqParser.Null_notnullContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_table(@NotNull sybaseiqParser.Create_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#search_condition_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSearch_condition_list(@NotNull sybaseiqParser.Search_condition_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#rowset_function}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitRowset_function(@NotNull sybaseiqParser.Rowset_functionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#drop_view}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDrop_view(@NotNull sybaseiqParser.Drop_viewContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#unary_operator_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUnary_operator_expression(@NotNull sybaseiqParser.Unary_operator_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#procedure_param}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitProcedure_param(@NotNull sybaseiqParser.Procedure_paramContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#index_column_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIndex_column_name(@NotNull sybaseiqParser.Index_column_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#with_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWith_expression(@NotNull sybaseiqParser.With_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#permission_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPermission_list(@NotNull sybaseiqParser.Permission_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#then_condition_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitThen_condition_list(@NotNull sybaseiqParser.Then_condition_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#begin_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBegin_statement(@NotNull sybaseiqParser.Begin_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#aggregate_windowed_function}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAggregate_windowed_function(@NotNull sybaseiqParser.Aggregate_windowed_functionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#add_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAdd_list(@NotNull sybaseiqParser.Add_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#subquery_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSubquery_expression(@NotNull sybaseiqParser.Subquery_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#string_concatenation}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitString_concatenation(@NotNull sybaseiqParser.String_concatenationContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_index}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_index(@NotNull sybaseiqParser.Create_indexContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#opendatasource}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOpendatasource(@NotNull sybaseiqParser.OpendatasourceContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#for_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFor_clause(@NotNull sybaseiqParser.For_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#view_attribute}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitView_attribute(@NotNull sybaseiqParser.View_attributeContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#index_options}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIndex_options(@NotNull sybaseiqParser.Index_optionsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#permission}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPermission(@NotNull sybaseiqParser.PermissionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#ddl_object}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDdl_object(@NotNull sybaseiqParser.Ddl_objectContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#row_or_range_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitRow_or_range_clause(@NotNull sybaseiqParser.Row_or_range_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_name_with_hint}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_name_with_hint(@NotNull sybaseiqParser.Table_name_with_hintContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#select_list_elem}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSelect_list_elem(@NotNull sybaseiqParser.Select_list_elemContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#database_option}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDatabase_option(@NotNull sybaseiqParser.Database_optionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_name_list}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_name_list(@NotNull sybaseiqParser.Column_name_listContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#sign}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSign(@NotNull sybaseiqParser.SignContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#simple_id}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSimple_id(@NotNull sybaseiqParser.Simple_idContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_local_temporary_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_local_temporary_table(@NotNull sybaseiqParser.Declare_local_temporary_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#full_table_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitFull_table_name(@NotNull sybaseiqParser.Full_table_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#search_condition_not}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSearch_condition_not(@NotNull sybaseiqParser.Search_condition_notContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#common_table_expression}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCommon_table_expression(@NotNull sybaseiqParser.Common_table_expressionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#ddl_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDdl_clause(@NotNull sybaseiqParser.Ddl_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#procedure_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitProcedure_name(@NotNull sybaseiqParser.Procedure_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#print_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitPrint_statement(@NotNull sybaseiqParser.Print_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#declare_type}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDeclare_type(@NotNull sybaseiqParser.Declare_typeContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#alter_table}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAlter_table(@NotNull sybaseiqParser.Alter_tableContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_alias}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_alias(@NotNull sybaseiqParser.Table_aliasContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#message_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitMessage_statement(@NotNull sybaseiqParser.Message_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_def_table_constraint}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_def_table_constraint(@NotNull sybaseiqParser.Column_def_table_constraintContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#then_condition}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitThen_condition(@NotNull sybaseiqParser.Then_conditionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#column_constraint}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitColumn_constraint(@NotNull sybaseiqParser.Column_constraintContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#location_options}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitLocation_options(@NotNull sybaseiqParser.Location_optionsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#exception_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitException_statement(@NotNull sybaseiqParser.Exception_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#execute_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitExecute_statement(@NotNull sybaseiqParser.Execute_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#insert_select_load_options}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitInsert_select_load_options(@NotNull sybaseiqParser.Insert_select_load_optionsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#window_frame_bound}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWindow_frame_bound(@NotNull sybaseiqParser.Window_frame_boundContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#update_elem}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitUpdate_elem(@NotNull sybaseiqParser.Update_elemContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#search_condition_or}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSearch_condition_or(@NotNull sybaseiqParser.Search_condition_orContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#while_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWhile_statement(@NotNull sybaseiqParser.While_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_source_item_joined}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_source_item_joined(@NotNull sybaseiqParser.Table_source_item_joinedContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#output_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOutput_clause(@NotNull sybaseiqParser.Output_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#loop_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitLoop_statement(@NotNull sybaseiqParser.Loop_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#id}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitId(@NotNull sybaseiqParser.IdContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#delete_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDelete_statement(@NotNull sybaseiqParser.Delete_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#drop_index}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDrop_index(@NotNull sybaseiqParser.Drop_indexContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#assignment_operator}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitAssignment_operator(@NotNull sybaseiqParser.Assignment_operatorContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#begin_parallel_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitBegin_parallel_statement(@NotNull sybaseiqParser.Begin_parallel_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#insert_load_options}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitInsert_load_options(@NotNull sybaseiqParser.Insert_load_optionsContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#table_name}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTable_name(@NotNull sybaseiqParser.Table_nameContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#raiseerror_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitRaiseerror_statement(@NotNull sybaseiqParser.Raiseerror_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#case_expr}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCase_expr(@NotNull sybaseiqParser.Case_exprContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#window_frame_following}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWindow_frame_following(@NotNull sybaseiqParser.Window_frame_followingContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#window_frame_extent}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWindow_frame_extent(@NotNull sybaseiqParser.Window_frame_extentContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#index_option}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIndex_option(@NotNull sybaseiqParser.Index_optionContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#constant}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitConstant(@NotNull sybaseiqParser.ConstantContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#create_association}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCreate_association(@NotNull sybaseiqParser.Create_associationContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#dml_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDml_clause(@NotNull sybaseiqParser.Dml_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#execute_statement_arg}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitExecute_statement_arg(@NotNull sybaseiqParser.Execute_statement_argContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#comment_on_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitComment_on_statement(@NotNull sybaseiqParser.Comment_on_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#index_value}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitIndex_value(@NotNull sybaseiqParser.Index_valueContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#call_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitCall_statement(@NotNull sybaseiqParser.Call_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#window_frame_preceding}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitWindow_frame_preceding(@NotNull sybaseiqParser.Window_frame_precedingContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#transaction_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitTransaction_statement(@NotNull sybaseiqParser.Transaction_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#subquery}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitSubquery(@NotNull sybaseiqParser.SubqueryContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#go_statement}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitGo_statement(@NotNull sybaseiqParser.Go_statementContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#option_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOption_clause(@NotNull sybaseiqParser.Option_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#order_by_clause}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitOrder_by_clause(@NotNull sybaseiqParser.Order_by_clauseContext ctx);

	/**
	 * Visit a parse tree produced by {@link sybaseiqParser#datepart}.
	 * @param ctx the parse tree
	 * @return the visitor result
	 */
	T visitDatepart(@NotNull sybaseiqParser.DatepartContext ctx);
}